version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=enzo
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=db_desarrollo
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_desarrollo
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=enzo@musa.la
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
