# Usar la imagen oficial de PostgreSQL
FROM postgres:14

#Definir variables de entorno
ENV POSTGRES_USER=enzo
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=db_desarrollo

#Exponer el puerto 5432 para PostgreSQL
EXPOSE 5432